<?php
const ACTION_MAP = [
    'Список користувачів' => 'userList',
    'Додати користувача' => 'addUser',
    'Видалити користувача' => 'deleteUser',
    'Редагувати користувача' => 'editUser',
    'Список магазинів' => 'storeList',
    'Додати магазин' => 'addStore',
    'Видалити магазин' => 'deleteStore',
    'Редагувати магазин' => 'editStore',
    
    'Список замовлень' => 'viewOrders',
    'Отримати звіт' => 'sumOrders',
    'Додати категорію' => 'addCategory',
    'Видалити категорію' => 'deleteCategory',
    'Редагувати категорію' => 'editCategory',
    'Додати правило' => 'addRule',
    'Видалити правило' => 'deleteRule',
    'Список позицій' => 'viewItem',
    'Редагувати позицію' => 'editItem',
    'Додати позицію' => 'addItem',
    'Видалити позицію' => 'deleteItem',
    
    'Історія замовлень' => 'orderHistory',
    'Каталог товарів' => 'productCatalog',
    'Поточне замовлення' => 'currentOrder',
];

const VIEW_MAP = [
    'userList' => 'line',
    'addUser' => 'modal',
    'deleteUser' => 'modal',
    'editUser' => 'modal',
    'storeList' => 'line',
    'addStore' => 'modal',
    'deleteStore' => 'modal',
    'editStore' => 'modal',
    
    'viewOrders' => 'line',
    'sumOrders' => 'line',
    'addCategory' => 'modal',
    'deleteCategory' => 'modal',
    'editCategory' => 'modal',
    'addRule' => 'modal',
    'deleteRule' => 'modal',
    'viewItem' => 'cardsPositions',
    'editItem' => 'modalEditItem',
    'addItem' => 'modalAddItem',
    'deleteItem' => 'modal',
    'getProduct' => 'null',
    
    'orderHistory' => 'line',
    'productCatalog' => 'cardsPositionsOrder',
    'currentOrder' => 'lineCurrentOrder',
];